### PR TITLE
Improved sendmail configuration

### PR DESCRIPTION
**Pull request by StevenWingett**
The configuring of sendmail has been improved in the setup process and works for me.  It would be useful to know if this works for other users and on other systems.  If this is all good, then this could form the basis of a Labrador Docker container at some point in the future.

Cheers,
Steven

### CODE REVIEW

**Comment by ewels** [comment]
Looks like you haven't configured `git` with your GitHub.com email address - some of your commits here are not attributed to you. See https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git

```bash
git config --global user.email "email@example.com"
```

**Comment by ewels** [comment]
(or if you have, then maybe that email address hasn't been added to your GitHub profile)

**Review by ewels — APPROVED** [review]
Nice! Feels a bit wrong to be doing so much installation and configuration inside a docker container / image, would definitely be good to put this into a `Dockerfile` (especially if we can then run with certain command line flags to do the customisation).

But what you have here in this PR is definitely an improvement over what is already in the repo, so happy to merge 👍🏻 

Thanks!

**Comment by StevenWingett** [comment]
I agree.  So long as this works for other people then we just need to translate these commands into a Docker recipe.  😀

Cheers,
Steven

**Pull request merged**
