### PR TITLE
Added Docker instructions to documentation

### PR DESCRIPTION
**Pull request by StevenWingett**
Updated documentation to describe how to run Labrador using a webserver within a Docker container.  This should (in theory) be easier to set up and more portable between different systems.

### CODE REVIEW

**Review by ewels — COMMENTED** [review]
Do you need to `sudo` everything? I don’t usually do this when using docker on Mac..

If you don’t mind the faff I prefer to use triple-back-tick code blocks for markdown instead of indentation. I think it’s clearer, plus you can specify bash as the code language and the commands will be syntax highlighted.

Thank you for this! One day it might be nice to make a docker image specifically for Labrador. If you’re nice I’ll have a think about it :) Then we can pre-install sendmail and the Labrador source code which would make life a bit simpler.

**Comment by StevenWingett** [comment]
Ok.  I do seem to need sudo, but I can drop if you prefer?

I was following the indent code style used already in the document.

My thoughts as well regarding the Labrador container, but it would be good to get this working first.

Cheers,
Steven

**Comment by ewels** [comment]
> I was following the indent code style used already in the document.

Wow I really did write this a long time ago 😆

**Comment by ewels** [comment]
Ok I fixed it 😅

**Comment by ewels** [comment]
Right and I also dropped the `sudo` but added a note that it may be required 👍🏻

**Pull request merged**
